### ISSUE TITLE
Delete file does not clean properly the ZIM render widget

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#107]
If you delete the file which is currently in use, then the last visited page is still open (after quitting settings)... but nothing happens if you click on a link. IMO, this page should simply be removed and the welcome one should be display in place (the one with the button to go to the library).

**Comment by automactic** [comment]
> nothing happens if you click on a link

I think an alert / popup should be displayed to let user know the file is unavailable and the article cannot be loaded, but we should not make the current article disappear. Just like the browser doesn't disappear if you unplug the ethernet cable or disconnect wifi.

@kelson42 what do you think?

**Comment by automactic** [comment]
<img width="320" alt="Screenshot 2020-06-20 at 5 07 28 PM" src="https://user-images.githubusercontent.com/8294252/85212190-56826b80-b31e-11ea-901d-465e2f3a311c.png">

Since I did not get a response with the above proposal, I went ahead with it. Now an alert will be displayed if the file used to load content of a url is deleted.
