### ISSUE TITLE
Suggestion: Option to delete bookmarks with the package

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#112]
I don't see the point in keeping bookmarks for a package that does not exist anymore on the device. But since this is the standard behaviour currently («Delete File: This will delete the zim file but keep the bookmarks.») there may be reasons for this.

So I would suggest that we implement at least an option «Delete bookmarks for this package as well». Because if you prefer clean bookmarks (like I do), deleting them one by one is not a real alternative.

**Comment by kelson42** [comment]
If the the bookmark is attached to the "name" of the ZIM file (and not to the filename, id) then you could reuse these bookmarks at some point with a version with more pictures, or even a more recent version. 

Maybe we could just "blind" them?

**Comment by martin8032** [comment]
Hiding the bookmarks of a deleted package would be the minimal solution IMHO.

Personally I'd prefer to have the choice between keeping and deleting the bookmarks.

**Comment by automactic** [comment]
@martin8032, when you add a bookmark, the bookmark it tied to a package (aka book / zim file), since the bookmark relies on resources in it's package to be loaded. 

If the kiwix app just have add / remove bookmark function, it wouldn't be very useful. Since when a new version of the package is released, user is gonna replace old package with a new one. All bookmarks tied with the old package will no longer work. 

To address this issue, we added "name" field to zim files. The "name" is an identifier that is persistent between releases of the same package (e.g. wikimed_nopic, etc.) When a new zim file is added, the "name" field allow the app to check if bookmarks of a older version could be migrated. That's the idea. 

All issue related to bookmark will be properly addressed in the next major release (for example, 1.10). When the time comes, we will have ability to manage bookmarks by tags or folders, apply different filters to bookmarks, export bookmark database as a file, backup bookmark using iCloud, etc. But before all these features are added, we have to provide a way to make it worthwhile to spend the effort to bookmark stuff and to manage a collection of articles.

**Comment by martin8032** [comment]
OK, thank you for this background information.

**Comment by automactic** [comment]
No action is planned to be taken from this ticket. Thanks for the suggestions
