### ISSUE TITLE
TEDMED videos have no sound

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#144]
From OTRS user:
"I’ve downloaded TED MED (https://download.kiwix.org/zim/zim/ted/tedmed_en_all_2018-06.zim) on my iPhone and the sound doesn’t play.

I then downloaded it on my iMac and the sound still does not play.

The videos play fine."

Edit: same problem with TED Science https://download.kiwix.org/zim/zim/ted/ted_en_science_2018-07.zim

**Comment by kelson42** [comment]
Yes, there is a kind of problem in the support of video (on iOS too BTW), we moved around a year ago to mp4 because this is officially supported by Apple, but we seem to have an other problem. I tried to identify it but first playing with kiwix-serve, and then I discovered an other bug, so basically I was tempting to get that one fixed first. See https://github.com/kiwix/kiwix-tools/issues/148

**Comment by bmenard1** [comment]
Same problem for me: I downloaded many of the TED talks on an iPad but none of them plays with sound. This, unfortunately, makes these videos useless. Fixing this would be greatly appreciated.

**Comment by kelson42** [comment]
@rgaudin TEDMED being based on Youtube scraper, we should redo them and see if it works better with the last version of the scraper.

**Comment by rgaudin** [comment]
will try it with master (need to download its 16G first) and if not working we'll transfer this to zim-request

**Comment by kelson42** [comment]
@rgaudin Not really as I suspect this is a problem with the reader!

**Comment by kelson42** [comment]
@rgaudin @automactic With newly created youtube zim files (so good zim files) nothing works, even video can not be played.

**Comment by kelson42** [comment]
New TEDMED ZIM file is online and fixes the problem https://download.kiwix.org/zim/ted/tedmed_en_all_2020-01.zim
