### ISSUE TITLE
Merge ZIM variants/flavour of the same content in online library

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#148]
Currently multiple variants make multiple entries in the library. If we make one entry and then just before starting the download we propose the variants, this should be more user friendly for the users.

**Comment by automactic** [comment]
I need some API support for this

**Comment by kelson42** [comment]
What kind of API you would like? You would like to get variants grouped together?

**Comment by kelson42** [comment]
@automactic ? You should group them by the metadata "name".

**Comment by automactic** [comment]
@kelson42 Hey, let's have a discuss about this one.

As I understand, the issue wish to have files with the same `name` to be grouped as one entry in the secondary level list (all file of a category). I have some concerns regarding this proposal:

1. Analyzing English zim files. In most cases, zim files with the same `name` would have two variants; this number can go up to 4 or 5 but very unlikely (e.g. Wikipedia 100 has 4 variants). It is kinda pointless to show a group (e.g. Movies by Wikipedia), then only show user two items when navigating into it. It seems like there would be too many levels to navigate through until user can find what they want
2. For non wikipedia categories (e.g. Wikiquote), and "smaller" languages (e.g. Finnish), there are not really that many zim files to make categories -> groups -> files -> file structure really worth it, since there would be one or two item at each level, resulting in a mostly empty screen.
3. I was planning to add sorting to the non-grouped list of zim files in one category (the current secondary level navigation), which would be helpful when trying to find, say the newest English Wikipeida zim file. Adding an extra group level makes it difficult / pointless to implement sorting
4. I would argue the current list is "kinda" grouped already. All zim files with the same title are staying together after all. Why do we have to create another level?
5. What do we plan to do with zim files with empty `name`?

**Comment by kelson42** [comment]
> @kelson42 Hey, let's have a discuss about this one.
> 
> As I understand, the issue wish to have files with the same `name` to be grouped as one entry in the secondary level list (all file of a category). I have some concerns regarding this proposal:

Yes, this is what I meant. The merging effort should be done at the libkiwix level and therefore this ticket depends on https://github.com/kiwix/kiwix-lib/issues/421
 
>     1. Analyzing English zim files. In most cases, zim files with the same `name` would have two variants; this number can go up to 4 or 5 but very unlikely (e.g. Wikipedia 100 has 4 variants). It is kinda pointless to show a group (e.g. Movies by Wikipedia), then only show user two items when navigating into it. It seems like there would be too many levels to navigate through until user can find what they want

OK, in that case you disagree with the whole feature request. My opinion is that people are bored to get their online library filled with 2+ similar entries and would prefer to choose one to download and then be asked about the flavour. I don't really see it as a sub-category, more as a final choice to make before starting the download.
 
>     2. For non wikipedia categories (e.g. Wikiquote), and "smaller" languages (e.g. Finnish), there are not really that many zim files to make categories -> groups -> files -> file structure really worth it, since there would be one or two item at each level, resulting in a mostly empty screen.

Yes, but the category system navigation is not a must. I kind of believe/want that the free text search is the dominant way of finding contents.

>     3. I was planning to add sorting to the non-grouped list of zim files in one category (the current secondary level navigation), which would be helpful when trying to find, say the newest English Wikipeida zim file. Adding an extra group level makes it difficult / pointless to implement sorting

I'm not against sorting options. I don't have thought about both features correlated honestly. In general I believe that we should implement sorting option if we have a lot of results or/and we fail to achieve to display the relevant content on the top of the list automatically. Maybe we should try to do that first... and then if really impossible, implement sorting.

>     4. I would argue the current list is "kinda" grouped already. All zim files with the same title are staying together after all. Why do we have to create another level?

Yes they are grouped, but I prefer one list with 5 contents than a list of 10 contents with 5 "duplicates". One time I know what I want to download & read, I can choose the flavour.
 
>     5. What do we plan to do with zim files with empty `name`?

They won't be considered as a same content (so no flavour management). I believe we don't build such files anymore, but it is true this is a possible scenario.

> I do plan to rework some of the stuff in the library, so if you have ideas, now it is the time!

Yes, and sorry for the super later answer. In case this was not clear, we are running currently the effort to rationalize/optimize the library mgmt in libkiwix, see project https://github.com/orgs/kiwix/projects/8

**Comment by kelson42** [comment]
This is probably not the direction which is taken, we tend to list all zim files beside each others.
