### ISSUE TITLE
Sometimes zim files aren't excluded from iCloud backup

### ISSUE THREAD

**Issue by jberkel** [kiwix/apple#181]
(copied from #64)

Just had a failed iCloud backup after installing a 4GB ZIM file, cloud backup is disabled in Kiwix settings. IOS 13. Looking at the code, the exclude flag only gets set after the file has been opened, and is set per file. I started the install of the zim file and then put the app into  background, so it was installed but not excluded (which seems to happen when you first open it).

Perhaps it would be easier to create a separate directory for the zim files and set `isExcludedFromBackupKey` globally for that directory?

**Comment by automactic** [comment]
Hi @jberkel 

The idea behind file discovery in Kiwix is that what you see in iTunes / Files app is what you will get inside the app. So that id you do plug in your device to the computer and manage what zim file you want to use, the app would be kept in sync next time it become active. So I have to leave files in the document dir. 

Setting `isExcludedFromBackupKey` on the document dir also is not a super good idea, since:
> You can use this property to exclude cache and other app support files which are not needed in a backup. Some operations commonly made to user documents cause this property to be reset to false; consequently, do not use this property on user documents. [from documentation](https://developer.apple.com/documentation/foundation/urlresourcekey/1408756-isexcludedfrombackupkey)

So to have the app not back up your files inside Kiwix's document dir, you need to at least make the app active / foreground once to give it a chance to update. 

Another solution to your problem is to exclude kiwix from iCloud backup inside the system setting app

**Comment by jberkel** [comment]
> Setting isExcludedFromBackupKey on the document dir also is not a super good idea, since:

I wouldn't set it on the document directory itself, but on a sub directory (where files get downloaded to).

the exclude flag could be set again before starting a download, to make sure the directory is excluded.

> Another solution to your problem is to exclude kiwix from iCloud backup inside the system setting app

Kiwix is not listed under iCloud / iCloud backup, so not sure how to turn this off there

**Comment by automactic** [comment]
> I wouldn't set it on the document directory itself

It would have to be on the document dir if we want to apply this attribute to a dir, since user using iTunes to manage their zim files can and probably will put zim files directly inside the document dir. 

> Kiwix is not listed under iCloud / iCloud backup

It is on my device. See this [apple support doc](https://support.apple.com/en-us/HT204247#selectapps) for some more detail.

**Comment by jberkel** [comment]
> > Kiwix is not listed under iCloud / iCloud backup
> 
> It is on my device. See this [apple support doc](https://support.apple.com/en-us/HT204247#selectapps) for some more detail.

maybe an app only gets listed after something has been backed up? otherwise the list would be very long.

anyway, thanks for your reply, looks like this can't get easily fixed for now.

**Comment by automactic** [comment]
Looks like this issue can be resolved and no action will be taken at this point
