### ISSUE TITLE
macOS app does not open any more extern ZIM directly (1.11)

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#221]
Steps:
1 - Download a ZIM in the browser
2 - From the notification open it with Kiwix
3 - Kiwix start

I get:
* New content is in the library but the welcome page is not open anymore

I want:
* The ZIM file open at the welcome page (like it was in previous version).

**Comment by automactic** [comment]
Sure I can take a look at this later

**Comment by automactic** [comment]
What is the desired behavior here? Perhaps now we should open the main page of the file being double clicked on in a new tab? Now that we support multi-tabs?

**Comment by automactic** [comment]
Since there aren't any comments on the desired behavior, I am deciding how things should behave.

Consider the following three cases:

1. If app is not running, double click a zim file should directly display the main page of the file
2. If app is running and the current tab is displaying the welcome view, that tab will load up the main page of the zim file
3. If app is running and the current tab is *not* displaying the welcome page, open a new tab and load the main page of the zim file
