### ISSUE TITLE
Cannot play video 

### ISSUE THREAD

**Issue by automactic** [kiwix/apple#25]
In iOS app video cannot be played. Tested using French TedxLausanneChange2013 Mar18, 2015, 81.8MB.

Here is the video player in the HTML
`
<video class="vjs-tech" preload="true" data-setup="{&quot;autoplay&quot;: true, &quot;preload&quot;: &quot;true&quot;}" id="vjs_video_3_html5_api" autoplay="" controls=""></video>
`
It does't have the **source** element. (The [HTML video example](http://www.w3schools.com/html/html5_video.asp) from W3School has.) @kelson42, could this be mwoffliner's fault?

**Comment by automactic** [comment]
After some further investigation, I found that in the raw html, there indeed is a source tag.
`
<source src="../../I/The-sky-is-NOT-the-limit-live-the-change-Manu-Jindal-at-TEDxLausanneChange/video.webm" type="video/webm" />
`

**Comment by automactic** [comment]
This issue is not caused by the app itself. It's just iOS doesn't support webm.

**Comment by kelson42** [comment]
I re-open the issue as we have the issue and need a strategy.

So far I see the following alternatives:
* Use an external library to render the video properly in the HTML renderer (best solution)
* Replace in all our ZIM files, the usage of webm with mp4 (so far I can see this is impossible due to the license costs... but not 100% sure)
* Remove all ZIM with videos from the catalog for iOS
* If user want to play such a video, invite him to install a webm video player and make the whole stuff works well between kiwix and this third party app

**Comment by kelson42** [comment]
A few links:
* https://github.com/brion/OGVKit
* https://wiki.videolan.org/VLCKit/

**Comment by kelson42** [comment]
The fundamental problem has been solved. If video don't play now, this is a problem with the ZIM themselves. @rgaudin Would you agree to close that ticket?

**Comment by rgaudin** [comment]
No, it has only been solved for iOS. Do you want to open a separate bug for macOS?

**Comment by kelson42** [comment]
@rgaudin yes please if this is still not done. iOS and macOS versions of Kiwix should not have tickets in common.

**Comment by kelson42** [comment]
See also https://github.com/kiwix/apple/issues/189
