### ISSUE TITLE
should TOC be clickable?

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#253]
The Table of content is awesome to know what's in an article, especially Wikipedia's which opens folded but there's a sort of expectation that it would be clickable and lead to that part of the content.

It seemed so obvious that I though it was a bug but I then realized it's called *Outline* probably just for the purpose to emphasis it's not a TOC. Yet when it's empty the message says *Table of content not available* :)

So question is: was it intended to be clickable ? Would it be doable?

**Comment by automactic** [comment]
It is called outline because Table of Content does not fit the button label. And I don't think it is a good idea to name it TOC and assume everyone know what it stands for. But they are the same concept.

It is certainly clickable, and tapping on a row should take you to the respective section. What is when the app is able to figure out a outline / TOC structure based on `h1`, `h2`, ... When it can't figure out an outline structure, it will say "xxx is unavailable"

Also, I am not sure what the problem / question really is? Could you elaborate? Step to reproduce & expected behavior?

**Comment by rgaudin** [comment]
Cliking on any row just hides the TOC at the moment. Will check if I have the problem on every ZIMs

**Comment by rgaudin** [comment]
Tested again and actually first-level rows do trigger the jump to the clicked part but sub-levels don't do anything (except hide outline).

Tested on `wikipedia_fr_basketball`.

**Comment by automactic** [comment]
Lemme test out `wikipedia_fr_basketball` later, perhaps something is broken...

**Comment by automactic** [comment]
@rgaudin I think I know what is going on. The heading you want to navigate to has to be visible in the first place. If a heading is hidden, then the js to scroll to it obviously won't do anything.

Note that it is not the reader app's job to do zim file specific patches to properly expand sections. Just like no browser carry website specific patches / logic.

**Comment by rgaudin** [comment]
I understand the technical issue but it doesn't make it less disturbing from a user's standpoint : you click one, you're taken there, you click another one, nothing happens.

Marking as won't fix.

**Comment by automactic** [comment]
Why do we make the sections to be collapsed anyway? I personally find it annoying when I have to constantly expanding sections when reading. (especially when I am holding phone with one hand)

I have raised this in https://github.com/openzim/mwoffliner/issues/1124
