### ISSUE TITLE
iOS 1.12 returns wrong zim size

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#269]
Just noticed that wiktionary_en_simple_all_maxi_2020_05.zim shows up as 51.1 Mb when it is in fact 49MB (48.7MB according to Android)
Same thing with Wiktionary_en_maxi/nopic (5.75 and 5.24 MB shown instead of 5.4 and 4.9MB, respectively)

![IMG-20200601-WA0017](https://user-images.githubusercontent.com/21675885/83503846-043eef00-a4c4-11ea-8cbb-e5de3e3aefd1.jpg)

**Comment by rgaudin** [comment]
FYI `5.14MB` == `4.9 MiB` [more on WP](https://en.wikipedia.org/wiki/Octet_(computing)#Unit_multiples)

**Comment by Popolechien** [comment]
damn, I thought that was it and did check, but at the wrong place obviously.

**Comment by rgaudin** [comment]
Not sure we should close. We should settle on what notation tu use everywhere (all readers) and make sure it's used and properly noted everywhere

**Comment by kelson42** [comment]
It should be define here was is the correct thing to display.

**Comment by rgaudin** [comment]
OK, I've looked into the source and there's something interesting.

Regarding `wiktionary_en_simple_all_maxi_2020-05`, the actual size returned by OPDS is `51076096` bytes so it's either `51.08 MB` or `48.71 MiB`.

My guess was thus right, it's a notation issue. iOS app uses MB properly (and rounds it) while Android is using MiB, possibly displaying it as `MB` instead of `MiB` (haven't checked).

So unless we want iOS app to use MiB, this is not a bug and we should open one in Android (to use MiB notation or display MB)

Now interesting fact is that the `library.xml` (the library.kiwix.org source, nothing to do with OPDS) has this info as `size="49879"` so it's the actual size divided by 1024…

**Comment by automactic** [comment]
Not a bug

I think as long as the app is consistent with the OS, we are fine. For example, if file explorer reports `48.71 MB`, even if it should be technically be `48.71 MiB`, the app should still report `48.71 MB` on windows.

Not many people are aware of `MiB` vs `MB`. It will be much more confusing if the app reports different file size than the OS

**Comment by automactic** [comment]
The file size reported in the iOS app is the same as what iOS reports (e.g. in the Files app). I would be glad to have more discussion, but as far as I am concerned, there isn't anything to fix.

**Comment by rgaudin** [comment]
FYI, I checked and the Android app reports MiB noted MB. I did not open a ticket there are this is the default behavior on Android. So as @automactic suggested, as long as it's consistent with the platform it runs on, it's the proper behavior.
