### ISSUE TITLE
"Rate the app" invitation dialog should only display if device is online

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#28]
If the device is not connected to the internet, the user can not rate the app and it does not make sense to invite him to do so.

**Comment by automactic** [comment]
We will transition to `StoreKit` in the near future, so networking is handled by the system.

**Comment by kelson42** [comment]
@automactic Sorry but what does that mean exactly? It will be fixed in the future? If "yes" what will be the behaviour? Or this is imposible to fix the problem because we have no control?

**Comment by kelson42** [comment]
@automactic Does that problem has finally been fixed?

**Comment by automactic** [comment]
@kelson42 I do not have plan to do anything about this ticket. Details:

- the app redirect to the App Store to allow user to rate the app, so handling offline state should arguably be App Store app's job
- it is not really possible to conclusively determine if device is "online", you'd have to define what is "online" first. Is it connected to wifi? Is it can connect to `google.com` or `apps.apple.com`? Connected to wifi or cellular does not equal to connectivity
- it can create a worse experience where user open settings of the app, and "rate the app" does not immediately show up because it takes time to figure out if the device can connect to App Store 
- what is the point? it adds extra complexity to an area of the app user doesn't interact with very often

**Comment by kelson42** [comment]
@automactic OK, I believe as well that this is not that important that we need to invest a lot of time. Android provide an easy primitive to know if the device is connected to internet (wifi or data connection active). Was kind of assuming this is easy as well on iOS.
