### ISSUE TITLE
Unable to open external file directly

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#335]
Steps:
* download zim file via browser
* open download folder
* click on ZIM file and choose to open with Kiwix

I get:
* Kiwix started, but ZIM file welcome page not displayed and ZIM file not in local library

**Comment by automactic** [comment]
Which option did you choose inside kiwix after you tap on the file? I tested all three options and I cannot reproduce

**Comment by kelson42** [comment]
I don't know which options you are taking about. It should just launch Kiwix and directly open the according ZIM file, without any additional manipulation.

**Comment by michael-garofalo** [comment]
I was not able to reproduce this issue either. However, it sounds like it might be a permissions issue, as macOS can have access restrictions specific to certain directories — such as the Desktop folder, the Documents folder, and the Downloads folder.

@kelson42 — If you go to System Preferences > Security & Privacy > Privacy > Files & Folders — do you see “Kiwix” in the list of apps? I don't see it there, so I'm not sure where's a problem.

Perhaps this issue was already resolved or perhaps it's related to an older version of macOS. I'm running Monterey macOS 12.5.1.

**Comment by kelson42** [comment]
Not reproducable.
