### ISSUE TITLE
[URGENT] Hide all ZIM using tag "_sw:yes"

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#363]
As long as #341 is not implemented. Otherwise users might download content that they won't be able to read.

Official publishing of such files starts literally tomorrow.

**Comment by automactic** [comment]
What does `_sw:yes` mean? Does it mean the zim file require service worker to function? Or does it mean the zim file contain some content that require service worker but there can be other content that will work just fine without service worker?

It matters because:

1) it make a difference in the key / field name in the app's local database
2) if user did add a file to the app manually, I want to clearly communicate in UI with a warning

**Comment by kelson42** [comment]
I believe I don't understand your point 100% but will try to answer.

On https://wiki.openzim.org/wiki/Tags it is written "indicates wheter the ZIM file relies on Service Workers."

In the current use case, the ZIM file is not usable without service worker. At this stage, these files are AFAIK not usable *at all* on Kiwix iOS/macOS.

**Comment by automactic** [comment]
Cool, looks like the answer is -- the zim file require service worker to function (i.e. nothing will work, instead of only a selected few article / pages will not work)

**Comment by automactic** [comment]
Done. As always with these kind of library changes, expect the files meeting the removal criteria to be removed upon next library refresh (automatic or manual), and not immediately when the app is updated

**Comment by kelson42** [comment]
@automactic THX. Fixed by #367
