### ISSUE TITLE
Search bar and bug report button crash

### ISSUE THREAD

**Issue by MrFFox** [kiwix/apple#392]
App crashes when I press "bug report" button. It also used to crash when I pressed the search bar, but unexpectedly I stopped facing this issue. 
Device is: iPad Air 4th generation
iPadOS version is: 14.7.1 
Kiwix version is: 1.14.2

**Comment by automactic** [comment]
What do you mean by bug report button, I don't think I have added such a button.

The crash upon tapping on search bar issue, from some of the crash log of other people, it seem the crash happened inside a system framework. There were very little info in the traceback and since you (nor me) can consistently reproduce the issue, there is little I can do.

On a partially related note, I have recently identified two issues in search. One of them **maaaybe** helpful to avoid these kind of crashes. Please wait for the next release or the next TestFlight

**Comment by Bakr-Ali** [comment]
I have the crashing issue as well. As soon as I touch the search bar, the app crashes. It crashes every single time.
I was having it on the previous version, so I left the app until the latest update came out hoping it will fix the issue, but it didn’t.
Deleted the app and reinstalled without downloading any sources: the app doesn’t crash.
Downloaded the WikiMed zim: the app crashes immediately on touching the search bar.
Is there anyway I can help? The app is completely unusable now!

Device is: iPad Pro 1st generation
iPadOS version is: 14.4
Kiwix version is: 1.14.3

**Comment by kelson42** [comment]
Latest wikimed zim tested with latest tesflight on ipad... and not problem.

**Comment by automactic** [comment]
@Bakr-Ali Hey, you are right, I can see this is among of the top crashes in the past few weeks. However I cannot consistently reproduce it on my side. It seems to only happen to some people but not others. And the info I can get from the analytics are very limited on this specific case.

Since it seems like you could consistently reproduce the issue, would you like to test some beta builds out on TestFlight? I have uploaded a build (number 76), which contains changes _I think_ will fix it. If not, we will keep trying until we find out the problematic part.

Sign up to TestFlight using [this link](https://testflight.apple.com/join/pKozwnSU) and wait for build 76 to become available

**Comment by Bakr-Ali** [comment]
@automactic I’ve installed the latest build 76, the issue still persists.
Not sure if it helps but I’ve selected “share information” on the crash dialogue.

**Comment by automactic** [comment]
@Bakr-Ali Hey can you try build 77? thanks

**Comment by Bakr-Ali** [comment]
@automactic It works! Thanks!

**Comment by automactic** [comment]
@Bakr-Ali Hey could you try build 78 as well? Just want to make sure I did not break things from the additional changes, since it will be the version I submit to App Store

**Comment by Bakr-Ali** [comment]
@automactic Build 78 works fine too. 👍

**Comment by Bakr-Ali** [comment]
> App crashes when I press "bug report" button.

@automactic I’ve just re-read this GitHub issue and noticed this part above. I think what they meant by the "bug report" button is actually the "send feedback" button, and it indeed crashes the app when pressed.
