### ISSUE TITLE
Crashing when searching anything on Kiwix for iOS v 1.15

### ISSUE THREAD

**Issue by built2spill69** [kiwix/apple#418]
iOS / iPadOS - iPad Pro 2020

When typing any character after clicking on the search bar, Kiwix crashes. The same happens when instead of searching you click one of the previous search you made. Overall, the search fonction felt unstable for at least six months. Kiwix is basically unusable at the moment. I’m sure that you’ll finally be able to fix and improve that.

Thank you !

**Comment by built2spill69** [comment]
Issue was fixed by deleting the wiktionary file I was using and downloading it’s latest update from : https://wiki.kiwix.org/wiki/Content_in_all_languages
Wiktionary files aren’t up to date in the native file downloader ; an easy fix may be to force any zim to be updated after Kiwix update is installed

**Comment by built2spill69** [comment]
Here it is ; the dictionary that was causing the issue is the one I highlighted on the screenshot.
https://ibb.co/CvLxm5y

About the library update : this is my fault, I didn’t notice before your message that you can update Kiwix’s libraries. Moreover, library updates were disabled ; I enabled them and yes, the available dictionaries are now up to date.

Once again I apologize for the « non issue » I made. Thank you.

**Comment by built2spill69** [comment]
Let me add that I was a few reviews on the App Store mentioning the « crashing whenever you search a word » after Kiwi’s got updated. It may be a great move to answer to these people who in fact simply haven’t seen that you have to update Kiwix’s libraries to fix the issue.
Updating the libraries also seems to fix this issue described in a few comments : typing a word in the search field often shows it’s relatives rather than the word itself. For instance, typing « voler » previously showed it’s conjugated forms such as « volerais », « volerons », etc.

**Comment by automactic** [comment]
@built2spill69 Hey, in the upcoming version of kiwix for iOS app (v1.15.3), I am reverting the code that handles zim files (libkiwix and libzim) to a older but stable version. It is likely it will resolve the issue you are having with the particular wiktionary file.

> It may be a great move to answer to these people who in fact simply haven’t seen that you have to update Kiwix’s libraries to fix the issue.

I do wish I could respond to some user feedback / review more often. But since kiwix is not my 9-5 day job, I hope you could understand why I am not doing that sometimes due to time constraints.

I will consider this matter closed for now, thank you for your feedback. Please do try the version 1.15.3 once it is released. If the issue with the wiktionary file persists, feel free to reopen this issue, I am happy to take another look.
