### ISSUE TITLE
Possible fix for the crashes happening while searching 

### ISSUE THREAD

**Issue by built2spill69** [kiwix/apple#456]
I had a wiktionary zim downloaded on Kiwix and nothing else.
This led to many crashes while typing words into the search box, as seen on many other issues opened on GitHub.
However, by adding Wikipedia’s zim file, all the crashes stopped happening. While searching, both libraries are checked : if I uncheck one of them, the crashes are happening again. 
I’m not a technician by any mean, and can’t explain what is going on. Anyway, I’m posting this hoping it could help both developers and users fixing things up. Please keep maintaining that awesome app. Thank you

**Comment by built2spill69** [comment]
Technicalities ;
iPadOS 15.6
Kiwix v 1.15.6
French wiktionary ID a678979d
French Wikipedia ID fd56c1dc 
Both downloaded through Kiwix integrated zim search

**Comment by forekko** [comment]
Hi, @built2spill69, I have the same problem with Full German Wiktionary + Full German Klexikon (Wiki for children), everyday it is crashes, sometimes I have to type one word 3-5 times when it crashes again and again. 
I tried to install additionally different Wikipedia ZIMs, including small thematic, like Basketball (approx 30 MB), because I do not need to this ZIM's entries will appear in search results, only for bug cheating purposes, so while anticrash-ZIM have less articles, it is better for looking what I search for. 
Also I tried German Wikipedia Top 100 in this purpose and even Whole English Wikipedia (without details and images), approx 6 GB. 
But it does not works for me. Kiwix still crashes. 
> French Wikipedia ID fd56c1dc 
This ID not still available anymore, I checked Top and Whole French Wikipedias. What the type of Wiki you downloaded? Is it necessary to use 40 GB of your iOS's space for this issue? :-D
Thank you for your reply.

**Comment by kelson42** [comment]
We should check this is new `3.0.0` version to be release soon.

**Comment by built2spill69** [comment]
I'm sorry for this really late answer !
@forekko ; I've downloaded the last French Wikipedia's zim available ; at
the moment, ID c5d6d08f, 3 september 2022. To be fair 40GB isn't a lot to
me since I have nothing on my iPad excepting a few books and courses...
Anyway please keep in mind that I'm not sure this fixed the crashes issue ;
although I've experienced no crash for a month.

And this may be helpful or once again a placebo : while searching, typing
the words without any accent (ie. è, ê, à, (ie. ä für German) seems to fix
the empty searches issues as well as the crashes. For instance, try typing
"ecole" instead of 'école", "bucher" instead "bücher".

Thank you

**Comment by kelson42** [comment]
@built2spill69 Thx for reporting and updating the ticket. It seems thos bug has been fixed. Feel free to reopen or report any new issue.
