### ISSUE TITLE
Can't search non-english language in iOS

### ISSUE THREAD

**Issue by Alimjoo** [kiwix/apple#458]
cant search non-english languages in iOS version. For example, When i search "Turán theorem" in desktop version, it will show me the results, but in iOS version, it shows nothing.

**Comment by kelson42** [comment]
@Alimjoo What was your exact content on which you run this search?

**Comment by Alimjoo** [comment]
> @Alimjoo What was your exact content on which you run this search?

The content I'am searching for is `Turán's theorem`. When I type `Tur` in search bar, it will show some results, but when I type `Turá`, the result just show nothing. And I also type `á` alone in the search bar, it show nothing also. 

But macOS version works fine.

**Comment by kelson42** [comment]
@Alimjoo question is not what you search, but in which book/content/zim?

**Comment by Alimjoo** [comment]
English version of the Wikipedia and wikiquote.

**Comment by HiroyasuNishiyama** [comment]
Hi.
Similar problem occurs when searching Japanese Wikipedia.

My guess is that this is due to internal character encoding.
iOS and macOS use NFD (Normalization Form Canonical Decomposition) for character encoding. On the other hand, it seems that NFC (Normalization Form Canonical Composition) is used in the content. 
Since NFD represents some characters, such as umlauts, as a composite of two characters, it is assumed that the search fails. 
(See [here](https://en.wikipedia.org/wiki/Unicode_equivalence) for details on NFC and NFD)

I think that it can be solved by converting the search target string from NFD to NFC with `precomposedStringWithCanonicalMapping` in swift code.

**Comment by kelson42** [comment]
@Alimjoo The bug you have reported should be fixed in version 3.2. I have tested with wiktionary in German on iPad.
