### ISSUE TITLE
Improvements for favourites handling

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#53]
A long-touch is not common in iOS apps. Personally I find it very hard to remember that a long-touch on the star icon adds the current page as a favorite while a short-touch opens the favorites collection. I would prefer that touching the star icon opens a dropdown with the following options:

- «Add to favorites» / «Remove from favorites» (depending on the current status)
- «Show all favorites»

In addition the full-screen confirmation «Bookmarked» / «Removed» is a bit too much – coloring or uncoloring the star icon would be enough feedback.

**Comment by automactic** [comment]
About long tap vs menu, this is my reasoning:
- **long tap**: yes, you have to remember it, but it's just a single action
- **menu**: you'd have to tap, (maybe read the menu items),move finger, tap again to finish an action

About full-screen confirmation:
Agreed on bigger iPads, but personally think it should be fine on iPhones. We indeed just to flip colors in earlier version of kiwix, but since user's finger is covering the star button. User cannot see if the bookmark is added / removed, therefore has no idea when to lift up finger.

**Comment by automactic** [comment]
Close due to lack of activity
