### ISSUE TITLE
iOS 17.1 Zim list inaccessible

### ISSUE THREAD

**Issue by TheDoctorHD** [kiwix/apple#532]
On iOS 17.1, once a zim file is loaded there does not seem to be a way to exit the file, which would allow the user to either choose another, or download another to be used in tandem. The only solution I have found so far is deleting the zim file from the phone via storage management. This feels unintentional, though my experience with this app is limited so I am free to stand corrected. Maybe adding the "no file loaded" dialogues always could fix this?![image](https://github.com/kiwix/apple/assets/108246971/69852160-b9e8-4c49-a354-0ab41c14d6cd)

**Comment by juancarlosdmz** [comment]
I have the same issue on iOS 17.0.3, iPhone 13

**Comment by pawelostr** [comment]
I have the same problem, however the underlying issue is that *Side menu is inaccesible on iOS*. On iPad (and I guess Mac) the button is in upper left corner, but it's impossible to open the side menu on iOS. 

Since it's critical and possibly related to #523 - @automactic 
[IMG_0463](https://github.com/kiwix/apple/assets/26488603/e3d566e1-ede1-4ff0-9194-6ad74bfcda24)
[IMG_2150](https://github.com/kiwix/apple/assets/26488603/46df2488-060a-49fe-a46d-89d7bbedb628):
![IMG_2150](https://github.com/kiwix/apple/assets/26488603/46df2488-060a-49fe-a46d-89d7bbedb628)

**Comment by kelson42** [comment]
@automactic ?

**Comment by melvyn2** [comment]
This makes the app unusable currently.

**Comment by automactic** [comment]
Hi @melvyn2 @juancarlosdmz @TheDoctorHD, not exactly sure what you are trying to do here... You can long press the tabs button on the lower right (on iOS) to show the overflow menu (previously a circle with three dots), and from there you can access setting, library, main page, etc. Is that what you are looking for?

Maybe the problem is the discoverability of the overflow menu? I don't want there to be more than 6 buttons on the bottom bar, and currently there are too many secondary functionalities that are competing for that space

**Comment by juancarlosdmz** [comment]
Yes, that is the problem, it is not intuitive at all

**Comment by rgaudin** [comment]
I did not realize there was a different long-press action neither (iOS). I am glad others didn't ; makes me feel better. I like it now that I know it but some kind of hint/nudge seems necessary.

**Comment by TheDoctorHD** [comment]
Yeah, I am very glad of the overflow menu's existence so I feel there should be some kind of message or hint that long-pressing is an option as me and at least a few others missed this. I don't know how much of a priority adding such a hint would be though. Regardless, thank you for your help!

**Comment by kelson42** [comment]
> Maybe the problem is the discoverability of the overflow menu? I don't want there to be more than 6 buttons on the bottom bar, and currently there are too many secondary functionalities that are competing for that space

Yes, we could hide/move random button if we need place for essential feature, see #474

**Comment by kelson42** [comment]
It seems clear we need something better, too many users reported feeling lost because of this workflow.

**Comment by u35253** [comment]
AGREE: The long press on Tabs for overflow menu was totally undiscoverable to me.

RELIEF: I'm glad to have found the menu exists, though!  Thanks to this thread.  It had seemed that Kiwix (latest) for iOS 16 (latest) on iPhone XS had lost the built-in ability to download Zim files.

THOUGHTFULNESS: I'm sure people who use the other buttons (random, favorites, TOC) a lot would not like to see them moved to the overflow menu to make space for 3 dots button.  But there has to be room somewhere.

PROPOSAL: My idea is: maybe add a small button with 3 dots to the right of the inactive Search bar which is pretty wide right now (same place where Cancel shows up when search bar is in use).

**Comment by int19h** [comment]
Perhaps the dice (random article) button could be moved next to search textbox? It makes more sense there IMO, given what it does.
