### ISSUE TITLE
CD and Apple Store Versioning

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#545]
⚠️ I have a limited understanding of all this.

macOS and iOS apps are versioned using two data:

- `MARKETING_VERSION` which is the user-visible *main version*. It's a string and currently is `3.2`
- `CURRENT_PROJECT_VERSION` which is a build-number. It's an integer or float and currently is `119`.

Both are stored in file `Kiwix.xcodeproj/project.pbxproj`

Apple Store also references the `MARKETING_VERSION` one as *App Store version*.

The Store obviously keeps an history of builds sent to it and apparently manages versions as follows:

- A human creates a *Version* in the Store (per platform). That's a string. Builds for this version will need to have a matching `MARKETING_VERSION`
- When created, it is in a *Prepare Stage*.
- There can only be one Version in Preparation, so up to two version in store: one in a complete state (like *Ready for Sale*) and one in prep
- In Prepare stages, we can upload builds for this *target version*.
- If we have no Version in Prep, we can't send builds, those are rejected.
- If we build offline and send, we must bump the build-number first or store will reject the build.
- If we build with App-Store credentials (what we now do in CD), build-number is automatically incremented.
- Each build sent creates a candidate for Test Flight.

We thus **need to decide on a process** to manage those Versions and what we want to do in CD:

- When/how/who manages the Store versions
- When/how to manage version and build-number in source code
- When to submit a build to the Store.

Note that when building for direct distribution (macOS dmg), it doesn't matter. We can build over and over the same `3.2 (119)` and notarize it.

**Comment by kelson42** [comment]
@rgaudin Thank you for asking the right questions! So far @automactic has handled this process manually and because he was alone on the project, following his own unwritten rules. Considering that we have now a CD and more people involved in the development, things have to be different, written and hopefully clearer. Here is what I propose.

First, in a matter of simplicity and coherence, I want AFAP to follow here the same approach as for other repository, ie.:
* `MARKETING_VERSION` (or Apple Store version) is the public facing and the most important thing. Here what is really important is to achieve a bijection between version and changelog. If we publish a version `x.y.z` then this version is a full release and there is no way back, any change has to be made in an other version number.
* `MARKETING_VERSION` should follow [Sementic versioning](https://semver.org/)
* There is a clear process to release with changelog, release ticket, milestone, software version update and release event, ... Actually would be a good idea to make a first version of such a release ticket to list what has to be done at this time to release properly.
* `CURRENT_PROJECT_VERSION` seems a technical thing and I recommend to auto-increment it so nobody has to take care of this. That said auto-incrementation should be done smartly to avoid any potential conflicts.

Then we have a few things which are less clear to me:
* Should we use Testflight all the time: each time we improve `main` we upload a new verrsion to Testflight. I think that would be quite elegant and handy
* How to handle dev versions versionning, which is an unresolved problem for the whole organisation so far. I would keep that aside for the moment.

@rgaudin Hope this answer your questions. Any feedback obviously welcome on this proposal.

**Comment by rgaudin** [comment]
OK, so from this and the discussion we had, I'd add:

- At all times, we should have two versions in ASC (App Store Connect)
  - latest released (offered in store)
  - dev version (next to be released)
- dev version could be named `dev`, `nightly` or anything else. While it's not perfect, I believe it's less confusing to have a named, numberless version for dev than a moving target of a tentative next version (which semantic versioning have us change)
- build number would stay as it is in the repo (latest release) and be auto-incremented transparently (using fastlane and/or apple)
- dev should be able to *push to ASC/Testflight* using a prefixed-tag
- it's dev's responsibility to update TestFlight description/comment in this case (when introducing new features)
- CD would push to ASC (in addition to trigger tag) **weekly** and **only if HEAD changed**. This is to allow testers to test actual code and not be overwhelmed by daily builds.
- release process (with the ticket and all) thus mandates that once we are ready:
   - we first request Review by Apple
   - wait for review/fix/re-submit/re-request (obviously)
   - then tag the corresponding commit and make a release on github
   - ➡️ this implies that CD doesn't push to ASC on release and release are now mgmt and does not trigger CD. Seems more convenient than the alternative
- we use the **same version for both macOS and iOS**

**Comment by kelson42** [comment]
> * dev version could be named `dev`, `nightly` or anything else. While it's not perfect, I believe it's less confusing to have a named, numberless version for dev than a moving target of a tentative next version (which semantic versioning have us change)

Agree, even simpler, why not `testflight`?

**Comment by rgaudin** [comment]
Makes sense!

**Comment by BPerlakiH** [comment]
Ok, to sum up, what is possible from the above:

Currently we have app version 3.2 in store.
Our next release will be 3.3. This value is already on main branch.
We also have build number 133 set on the main branch.
This needs to change to 139 for the following reasons:
> Important: For macOS apps, build numbers must monotonically increase even across different versions. In other words, for macOS apps you cannot use the same build numbers again in different release trains. iOS apps have no such restriction and you can re-use the same build numbers again in different release trains.
see: https://developer.apple.com/library/archive/technotes/tn2420/_index.html

The latest build number on Testflight for macOS is 138 (under the not yet released version 3.2). 

Since we want our iOS and macOS versioning in sync, we need to increment this number accross different versions for both platforms.

What we want, is to have builds that are ready for testing, either via weekly uploads, or a git tag triggered builds. I think renaming the build number, and adding the word "testflight" is not very beneficial for us.
After a couple of manual git tags and weekly builds we will have:

## Version 3.3
- 143-testflight
- 142-testflight
- 141-testflight
- 140-testflight
- 139-testflight

Eg. if we are happy with the testing results of `143-testflight`, and we decide to release it, we want to rename it to `143` without the suffix.
I am not sure if this is the right process to follow, as we will need to / should re-test the new build `143` before the final submission to AppStore (as it can be theoretically/accidentally different from `143-testflight`).

We will probably end up with more `-testflight` builds than release builds, my feeling is that such distinction in naming won't help us in any way.

I suggest not to rename the builds itself for Testflight purposes, and use Testlight only for validating and testing AppStore release candidates.

The safest use of Testflight is to test a build binary and once it is OK, we are 100% sure that it is the very same that will be submitted to AppStore.

There are alternative ways for dev build distributions (outside of Testflight), that we can leverage for truely dev builds (debuggable binaries) if that is needed, but I think that is a whole new topic, not in the scope of this issue.

For the above reasons, **my suggestion** is to keep the proposed process of releasing:
- **use weekly or tag based triggers to upload to TestFlight**
- **increment the build number in sync for both iOS and macOS apps** (we can leverage apple's mechanism for this, I think), **it should be a pure integer value**

Testers will be informed automatically that there's a new build available via the TestFlight application, and they should always test the latest apps (which have the highest version and build version).

**Comment by rgaudin** [comment]
Looks OK but final suggestion is unclear. Can you update your suggestion with sample version numbers and when/how the build number is updated

**Comment by kelson42** [comment]
> * dev version could be named `dev`, `nightly` or anything else. While it's not perfect, I believe it's less confusing to have a named, numberless version for dev than a moving target of a tentative next version (which semantic versioning have us change)

Lets use „dev“

**Comment by kelson42** [comment]
Lets version should be 3.3.0, why not usinf proper sementic version8ng?

**Comment by kelson42** [comment]
Build number is a technical stuff and devs should better not have to deal with it as it can be automatically incremented.

Ok with the proposed approach: at some point validating a tesflight version to publish straight… but this implies:
* from the very beginning of a milestone put the new version number and keep changelog updated as anytime something in testflight can be released
* Once released in app store the release event of github shoukd be triggered to release binaries on download.kiwix.org…

**Comment by BPerlakiH** [comment]
@kelson42 Thanks for the feedback.
> from the very beginning of a milestone put the new version number and keep changelog updated as anytime something in testflight can be released
I think this is doable. At the moment the version is set only in 1 place for kiwix app, so changing it is probably a ~1 minute work,
we might automate it somehow (catching when a milestone is created), but might not be that important.

> Once released in app store the release event of github shoukd be triggered to release binaries on download.kiwix.org…
I will add this to the list of todos. At the moment my understanding is that it is only for the macOS app to publish it in a .dmg format.
Possibly we can simply copy the last approved version file from: `master.download` to `download.kiwix.org`, without the need to rebuild it (again argument being here, that we want to make sure it's identical to the released one, which is well... ~ almost true).

**Comment by BPerlakiH** [comment]
@rgaudin 
> Looks OK but final suggestion is unclear. Can you update your suggestion with sample version numbers and when/how the build number is updated
I will look into this, what is the simplest way to auto increment the build number. From what I know that the macOS part should be handled by Apple on the TestFlight end, but will see how we can leverage that to make sure the iOS one is in sync as well.

**Comment by BPerlakiH** [comment]
So the suggested versioning will look more or less the following way, please note, this is just an example, I made up the dates and the sequence of triggers

## 3.3.0
- 142 <- triggered by Github tag prefixed with "testflight" on 15 Feb
- 141 <-  triggered by weekly on 12 Feb
- 140  <- triggered by Github tag prefixed with "testflight" on 7 Feb
- 139  <- triggered by weekly on 5 Feb

Now at this stage we say, we are happy with 3.3.0 (144), put it on AppStore,
create milestone eg. for version 3.4.0, update main branch with this number, 
copy the release/3.3.0 version on FTP to the right place (that's my current understanding of this),
and the whole process starts again for version 3.4.0

At this point we can think about, if we want to automate the milestone / version change / FTP handling bit.

Obviously in the meantime, we will have CI running for each and every PR pushed against main, and nightly running as well on main branch.

**Comment by rgaudin** [comment]
Following our discussion:

- iOS and macOS have slightly different processes because for macOS we distribute out-of-the-Store while iOS is Store-only.
- We don't want to move files around on the _FTP_: a release is a dedicated build.

So the process is as you described (with testflight and _nighly_ dmg builds) for but once we're ready for a release:

- we request validation from Apple on the Store (both macOS and iOS) -> this eventually (can take iterations) becomes the Store versions
- once we have an accepted macOS version on the Store, we create a _release_ on Github, reusing the same tag that produced the testflight build. That workflow will build and upload the dmg (and not do any testflisgt nor iOS stuff).

This will allow us to have App Store and dmg identical (from same source code) while benefiting from testflight flexibility.

**Comment by kelson42** [comment]
I will create a release issue with a checklist comform to this process.

**Comment by BPerlakiH** [comment]
As discussed, GitHub Action stores the commit SHA of the run weekly build, based on this we can use the same commit and base our post App Store release workflow on that.
