### ISSUE TITLE
Why DWDS show libkiwix version 12.1.0 considering it compiles with libkiwix 13.0.0?

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#558]
<img width="1024" alt="image" src="https://github.com/kiwix/apple/assets/1029718/115ab7e9-6ff7-4f3e-96bc-8aaf853e8bc5">

**Comment by rgaudin** [comment]
I see the same thing, even on a local build of iOS… It's not an issue with your version or the version in testflight.
Code is dynamic.
macOS versions are OK

<img width="662" alt="Screenshot 2023-11-27 at 08 36 21" src="https://github.com/kiwix/apple/assets/57929/d7bb9343-9c5c-4016-bb28-a3c115340192">

It doesn't look like we've published a release in the wrong order

- [libkiwix-version-bumped-merge](https://github.com/kiwix/libkiwix/commit/a959800173cc8f306b040388b4aa84b0d8843c98) at 2023-11-17 13:13
- [kiwix-build-release-commit](https://github.com/kiwix/kiwix-build/commit/b97e5d20b8f183576476e6e581f03044516e1be0) at 2023-11-17 14:49
- [action-for-apple_static_all](https://github.com/kiwix/kiwix-build/actions/runs/6905519602/job/18788483427) at 2023-11-17 15:26
- [File uploaded](https://download.kiwix.org/release/libkiwix/libkiwix_xcframework-13.0.0.tar.gz) at 2023-11-17 15:29

I don't think it can be due to deps from before the release, as we rebuild our projects always ; and that's visible in that action:

```
build libkiwix (iOS_arm64):
  configure libkiwix : OK (3.6s)
  compile libkiwix : OK (29.5s)
  test libkiwix : OK (0.4s)
  install libkiwix : OK (0.4s)
```

I've recompiled the xcframework locally (using kiwix-build) and when using it it works

We're not using a redirect in the actions and we only have one realease so no risk of using the incorrect one.

So I re-downloaded https://download.kiwix.org/release/libkiwix/libkiwix_xcframework-13.0.0.tar.gz and recompiled using it… but it's working 🤔

![Screenshot 2023-11-27 at 09 20 53](https://github.com/kiwix/apple/assets/57929/cc678668-b0ca-4e01-b657-c2d62c4d7c75)


At this point my theory would be that you have Testflight's version which has been overriden by @BPerlakiH who is not using the release libkiwix-13 but a previous nightly of a custom build that's not from current HEAD

**Comment by BPerlakiH** [comment]
The latest build 124 for DWDS contains libkiwix 13.0.0
