### ISSUE TITLE
Add string documentation

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#561]
Using the language code `qqq`. This language should obviously not be put in the binary.

Here is an example:
https://github.com/wikimedia/wikipedia-ios/tree/main/Wikipedia/Localizations/qqq.lproj

**Comment by kelson42** [comment]
@tvision251 Any news here?

**Comment by BPerlakiH** [comment]
It has been explicitly excluded, here: https://github.com/kiwix/apple/blob/main/project.yml#L113-L115
similarly we have it excluded for custom apps.

**Comment by kelson42** [comment]
@BPerlakiH This is a special code for documentation only, see https://translatewiki.net/wiki/FAQ#Special_private_language_codes_qqq,_qqx. if @tvision251 is not able to do it, would you?

**Comment by BPerlakiH** [comment]
I am not sure what is left to do here to be honest.
Currently these qqq files are already handled, they are added to git, but not included in the build.
Is there something else that needs to be done ?

**Comment by amire80** [comment]
I'm not the project manager, but from the point of view of good localization practices, this project needs the actual documentation. There are more than 230 strings in Apple Kiwix, and only 4 of them were documented (by myself).

All the strings in the English file need a corresponding documentation string in the qqq file: what are the parameters (such as %@), where does this string appear, what happens when it's clicked (if it's a button or a link), what does it describe (if it's an adjective), next to which strings it appears, etc. This documentation is the single most helpful resource for the volunteer translators.

MediaWiki is a separate project, but many MediaWiki volunteer translators also translate Kiwix, and that project has a good document with guidelines for writing and documenting messages:
https://www.mediawiki.org/wiki/Help:System_message

Almost all the tips in that document are applicable to Kiwix.

Thanks!

**Comment by BPerlakiH** [comment]
Fix it here:
https://github.com/kiwix/apple/pull/628/files#diff-769f3f1da239e5d09212a32e8b9e2b6bc878cc6a91fa483e7295b972c0ec1336
