### ISSUE TITLE
Specify/force language for custom apps

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#594]
Kiwix custom apps should have the ability to force UI language to a specific local.

**Comment by BPerlakiH** [comment]
The issues we tried to solve here:

> iOS selects the first language in the user’s language preferences list (in General > Language & Region of the Settings application). Then looks in your project for a matching .lproj folder. Such folder contains the relevant .strings files for the localized resource (e.g. Storyboard). Every language you support has a .lproj folder with the language prefix, e.g. ar.lproj, en.lproj, …etc. So, on app start, iOS selects the localization that it sees correct, and doesn’t refer to you (the developer) for such decision.
https://ahmedk92.github.io/2018/08/10/Arabic-As-A-Default-Language-for-Your-iOS-App.html

Injecting very early in the application lifecycle, according to the above:
https://sarunw.com/posts/what-do-main-uiapplicationmain-nsapplicationmain-mean/

Now the problem is that `Kiwix: App { init() {} }` function is not early enough to make this work.
Using the main.swift file solution, there's an issue, that we need to guess what is the synthesised implementation of @main for SwiftUI (for both iOS and macOS) by Apple. I consider this a very risky step just for the purpose of localisation.

**Comment by BPerlakiH** [comment]
Possible next step is to replace the Search bar implementations with "custom" cancel buttons, where we can use our localised strings, instead of the system provided ones on first launch.
