### ISSUE TITLE
No language selected

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#680]
<img width="662" alt="Screenshot 2024-03-04 at 12 02 05" src="https://github.com/kiwix/apple/assets/57929/75dd6dc3-6935-48ac-9e43-40cf22bc295a">

Clean environment, latest TF build (139):

- opened the App
- Was greeted with option to open a ZIM file or fetch the catalog.
- Didn't fetch the catalog, looked at the side bar menu, all empty until UI froze for a bit
- then I had the categories tab filled: it's all English
- Opened settings. Saw that no language is selected.

I might have misunderstood but I thought the default (`eng`) would be selected because showing a filtered (to `eng`) catalog with no language selected in settings is deceptive IMO.

**Comment by rgaudin** [comment]
As you can see on the screenshot ; the catalog has been fetched (automatically) but no language is listed…

**Comment by rgaudin** [comment]
Hitting refresh didn't solve issue. I had to quit and reopen the app for it to work

**Comment by kelson42** [comment]
@BPerlakiH I though all of this has been fixed!, do you know what's going on here?

**Comment by BPerlakiH** [comment]
Yes, it can be reproduced by a fresh install on macOS, if the library is not fetched the list of languages is empty. This is normal. The issue is that if the library is fetched from the settings panel (the one on the screenshot), the list of languages is not updated immediately. If you close the settings and re-open the list is refreshed.
The underlying logic and fetching mechanism works OK, it only needs a UI fix.

**Comment by kelson42** [comment]
OK, not sure if this is possible, but fetching shozld happen ASAP and UI shozld be kept in sync
