### ISSUE TITLE
Enable full screen mode

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#80]
Removes the interface, gives more room to the content. (Wikimed beta tester feedback)

**Comment by automactic** [comment]
The iOS app just have a navigation bar on top and another tool bar a the bottom of the screen (if on iPhones), so there should be plenty of screen space to read the articles. 

If we implement features that allow the bars to be hidden automatically when user scroll (or something similar), it would need quite a lot of time and programming to make a passable experience. This is definitely not the focus and is not likely to be implemented.

**Comment by kelson42** [comment]
@automactic This has been implemented on Android by a GCI student AFAIK. Wonder why this is so complicated? On the top of that having videos in fullscreen is not a nice-to-have, this is a must. I re-open this ticket. It's OK if you do not want to work on this, but we must have it at some point.

**Comment by automactic** [comment]
Oh, we definitely needs to be able to play videos in full screen mode, but you cannot play any videos currently on kiwix for iOS.

If you take a look at safari for iOS. the bar hides as page scroll up. If we want to have an experience comparable to safari, it is not easy. It would involve a lot of fine tuning. It is not easy as scroll down hide bar scroll up show bar.

**Comment by automactic** [comment]
@kelson42 I don't think we should do this. UIKit's build-in bars don't like to be shrinked or moved. To support things like this usually needs either hacks with build in bars or write my own bar. Both of which should be avoided unless we really need it. 

I personally think the spirit of this issue is to have the bars hidden when reading an article, so there could be more room for reading. I think it has nothing related to video

@Popolechien Are there a lot of user feedback related to hide bars when reading / reading space too small? I would appreciate your input here

**Comment by kelson42** [comment]
@automactic video fullscreen has to work. For the rest I can live without.

**Comment by rgaudin** [comment]
mentioning that the zims we create with videos have webm videos that are rendered by ogvjs in a <canvas /> and thus not deferred to the video subsystem.

**Comment by automactic** [comment]
But this ticket is not about fullscreen videos....

**Comment by kelson42** [comment]
@automactic yes, I have open a specific one #247

**Comment by automactic** [comment]
So shall we close this one?
