### ISSUE TITLE
Enable night mode

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#82]
(Wikimed beta tester feedback)

**Comment by kelson42** [comment]
@automactic Please keep one ticket per issue. If you want to gather tickets together you have many systems, like tags, milestones, projects. Rule about how to deal with tickets are give at https://github.com/kiwix/overview/blob/master/REPORT_BUG.md

**Comment by automactic** [comment]
We have added support for iOS 13 dark mode, which means the non-web component of the app already support dark mode. For content, we rely on content creators to properly support dark mode. And app level css / js injections are considered out of scope ATM, since we would prefer not to make assumption on content as a generic reader for offline html content

Yes, it is not prefect that contents are still in white background. See more at #231
