### ISSUE TITLE
Suggestion: Table of contents in sidebar (on large screens)

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#93]
On the iPad, the table of contents opens in tiny «bubble». This has two disadvantages:

1. There is only room for 7 to 10 entries, so you have to scroll a lot in longer TOCs.
2. The «bubble» closes immediately after you choose an entry. If you want to check several sections, you have to re-open the TOC every time.

Suggestion: Present the TOC in a sidebar (comparable to the sidebar of the mail app).

**Comment by automactic** [comment]
I have had a lot of internal debates regarding if I should show the table of content as a popover or side bar. So I have a few follow up questions to @martin8032:
- what if the table of content popover was made larger?
- what if we add a "pin" button to the popover, so it does not close as soon as you tap it?
- if we use a side menu, would it be a waste of space if the article is long but only has a few table of content items?
- how do you think about bookmarks presented in a popover?

**Comment by martin8032** [comment]
I generally don't like the popover at all. Using it for something like a TOC is not very iOS-like, it covers what's below it (therefore a pin function would not be helpful), it doesn't adapt in sitze to the screen orientation.

The TOC of the iPhone version is perfect: It looks great and is very usable. Simply put that one in a sidebar, and you have your solution. (Makes it more consistent as well.)

Same thing for the bookmarks, by the way.

**Comment by automactic** [comment]
Why is it not iOS like? The popover on iPad and modal view on iPhone are actually the same concrete presentation styles provided by the iOS SDK adapting to different screen size. The [`UIPopoverPresentationController`](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller) become a popover when there are space horizontally, become a modal when horizontally compact.

When the content to show is long at sometime and short at some other time, popover becomes a good idea, since it does not look bad when you don't have enough content and could accommodate large number of content (in terms of size of the popover and the content scrolling).

The size menu, while I agree it is cool and useful to view TOC and article side by side, it become a waste of space when not enough TOC item is in the article. Imagine the experience of a user browsing simple wikipedia. The experience of side menu would be quite bad, especially on portrait iPad, since most of the space on the left side of the screen will be wasted.

**Comment by automactic** [comment]
I am very glad we are having this conversation, since I had thought and debated a lot about this during the development process and was desperate to discussing pros and cons regarding this with someone else. 

It might be a good idea to have both and let users choose from setting. But of course I need time to do it.

**Comment by martin8032** [comment]
To leave the choice to the user would be ideal, of course. I can see your point as well. Since I have an iPad Pro with a 12" display, wasting some screen space is not my main concern. And if I really run out of space, I can still hide the sidebar. Permanently seeing the TOC on the other hand would be an advantage in certain situations.

**Comment by kelson42** [comment]
My two cents:
* Keep the button to make the TOC appear
* TOC should be displayed in a full sidebar (like it was I think in 1.8)
* Clicking on a TOC entry does not make the sidebar disappearing
* HTML rendering zone should be narrowed to avoid the sidebar to come over the text/content
* sidebar should appear on the right if rtl, on the left otherwise
* To make the sidebar disappear a slide left/right on the sidebar or re-clicking on the button

**Comment by automactic** [comment]
Aww, no one is a fan of the popover?

**Comment by martin8032** [comment]
I am a huge fan of the new sidebar in 1.9 (8)!

**Comment by kelson42** [comment]
Looks a lot more user friendly to mee to :) Should we close that ticket?
