### ISSUE TITLE
iPad only: No new packages available / crash on refresh

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#98]
On iPad Pro with iOS 11.2.1: I've upgraded from 1.9 (2) to 1.9 (3). When I want to download additional packages, I can see the categories, but they are empty. When I try to refresh the list (by pulling it down), the app crashes. (I tried this 3 times.)

**Comment by automactic** [comment]
Reminder: we don't care about app upgrade between betas, since there is no real world user out there that will encounter this scenario. 

In each app release cycle, we make sure two things work correctly before we release:
- app upgrade from previous release to current beta / release candidate
- app is freshly installed.
