### ISSUE TITLE
Minimal border

### ISSUE THREAD

**Issue by martin8032** [kiwix/apple#99]
When you set your font size to a higher value, the content really uses every pixel of the screen. Personally I think that a minimal white border left and right would improve the readability and look nicer.

**Comment by automactic** [comment]
Would you be able to elaborate your situation? Maybe providing some screenshots?

Stuff like this, toc, font size, line spacing, night mode, etc. needs to be solved at zim file level. The kiwix app, as a generic offline site reader, cannot come up with a "once and for all" solution / javascript to these problems, since sites can be dramatically different (wikipedia vs phet vs ted). 

As per our discussion on https://github.com/openzim/mwoffliner/issues/87

**Comment by martin8032** [comment]
I realize that the problem I mentioned is package-specific: The following screenshots are made with the font size set to 100%, 120% and 200% in an iPad Pro 12". While Wikibooks keeps a minimal white border, Wikivoyage does not. So we can close this issue, since its not related to the Kiwix iOS App.

**Wikibooks**
![wikibooks_fontsize_100_frontpage](https://user-images.githubusercontent.com/7620141/35943556-bb06de74-0c59-11e8-89ec-1bd9f61275e9.png)
![wikibooks_fontsize_120_frontpage](https://user-images.githubusercontent.com/7620141/35943557-bb332984-0c59-11e8-83f9-52b8224a6312.png)
![wikibooks_fontsize_200_frontpage](https://user-images.githubusercontent.com/7620141/35943560-bb82a806-0c59-11e8-8008-63d3f2d0d4d0.png)
![wikibooks_fontsize_200_article](https://user-images.githubusercontent.com/7620141/35943558-bb5cd31a-0c59-11e8-9f7b-031ace8e5079.png)

**Wikivoyage**
![wikivoyage_fontsize_100_article](https://user-images.githubusercontent.com/7620141/35943561-bbae864c-0c59-11e8-86dc-58e634ce3d2c.png)
![wikivoyage_fontsize_120_article](https://user-images.githubusercontent.com/7620141/35943563-bbdb6da6-0c59-11e8-9114-cc2d5b10d60b.png)
![wikivoyage_fontsize_200_article](https://user-images.githubusercontent.com/7620141/35943564-bc03a410-0c59-11e8-94c6-eb977a0ab4fa.png)

**Comment by automactic** [comment]
@martin8032 Thanks for the feedback! I hope this problem could be better addressed on the offline side in the future.
